name: TF Pre-Commit

permissions: {}

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  main:
    uses: getindata/github-workflows/.github/workflows/tf-pre-commit.yml@v0.3.1
    with:
      # tflint v0.46.0 is the latest version we can use with pre-commit v0.1.20
      # See .pre-commit-config.yaml for more details.
      tflint-version: v0.46.0
